/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.5.10"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    mavenCentral()
    maven("https://jitpack.io")
}

dependencies {
    // to be removed from Pulsar 1.8 https://github.com/apache/pulsar/issues/9045
    implementation("org.apache.avro:avro") { version { strictly("1.9.+") } }
    // add a logger
    implementation("org.slf4j:slf4j-simple:1.7.+")
    // infinitic framework
    implementation("io.infinitic:infinitic-factory:0.8.0")
    // infinitic dashboard
    implementation("io.infinitic:infinitic-dashboard:0.8.0")
}

application {
    // Define the main class for the application.
    mainClass.set("hello.world.AppKt")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_1_8.toString()
}

task("startWorkflow", JavaExec::class) {
    group = "infinitic"
    main = "hello.world.ClientKt"
    classpath = sourceSets["main"].runtimeClasspath
}

task("dashboard", JavaExec::class) {
    group = "infinitic"
    main = "hello.world.DashboardKt"
    classpath = sourceSets["main"].runtimeClasspath
    setArgsString("infinitic.yml")
}